name: バグ修正
description: バグの修正のテンプレート
title: "バグ"
labels: ["bug"]
assignees:
  - octocat
body:
  - type: input
    id : title
    attributes:
      label: バグの修正のタイトル
      placeholder: インサートページのフォームのバリデーションチェックバグ対応
      value: "バグ修正: "
    validations:
      required: true
  - type: textarea
    id: contents
    attributes:
      label: バグの内容
      description: バグの内容を具体的に記載してください。
      placeholder: 今のzodの実装だとurlでない文字列であるにも関わらすバリデーションチェックを通過してしまう。
      value: "# "
    validations:
      required: true
  - type: textarea
    id: resolve
    attributes:
      label: バグの解決
      description: バグ解決のためになにか提案などがあれば記入してください。
      placeholder: zodの公式ドキュメントから正しいバリデーションチェック構文を記載する。
      value: "# "
    validations:
      required: true
  - type: textarea
    id: memo
    attributes:
      label: その他
      description: その他メモ
      placeholder: なにか気になる点があれば記入してください。
      value: "- "
    validations:
      required: false