name: エンハンスメント
description: エンハンスメントのテンプレート
title: "エンハンスメント"
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: input
    id : title
    attributes:
      label: エンハンスメントのタイトル
      placeholder: 対象のurlを検索する機能を追加する
      value: "エンハンスメント: "
    validations:
      required: true
  - type: textarea
    id: contents
    attributes:
      label: エンハンスメントの内容
      description: エンハンスメントの内容を具体的に記載してください。
      placeholder: 対象のurlをステータスコードが正常の時であったり、ログが追加された日、表示件数などを検索、設定できるようにする。
      value: "# "
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: どうすれば実装できるか。
      description: エンハンスメントのためになにか提案などがあれば記入してください。
      placeholder: 検索機能を追加するにあたってクライアントコンポーネントかサーバーコンポーネントで実装するかの検討など
      value: "# "
    validations:
      required: true
  - type: textarea
    id: memo
    attributes:
      label: その他
      description: その他メモ
      placeholder: なにか気になる点があれば記入してください。
      value: "- "
    validations:
      required: false